title: Meaghan McManus
email: meaghan.mcmanus@psychol.uni-giessen.de
author: Meaghan McManus
description: under construction
# Remote theme
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme

# Custom CSS
just_the_docs:  
  custom_css:
    - "/assets/css/custom.css"

# Sidebar navigation order
nav_sort: case_insensitive
nav_order:
  - index.md
  - about.md
  - publications.md
  - updates.md
  - other.md

